[platformio]
default_envs = waveshare-185c

[env:waveshare-185c]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.flash_size = 16MB
board_build.partitions = huge_app.csv
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
lib_deps =
    bblanchon/ArduinoJson@^7.4.2
    links2004/WebSockets@^2.6.1
    rweather/Crypto@^0.4.0

[env:native]
platform = native
test_framework = unity
